### ISSUE TITLE
PrimitiveTripleInput doesn't work

### ISSUE THREAD

**Issue by paulhoule** [paulhoule/infovore#21]
Right now the PrimitiveTripleInput does not appear to work.  I get all the jars REGISTERED in Pig,  and then I try

t= LOAD '/005limeZ' USING com.ontology2.chopper.io.PrimitiveTripleInput() AS (s:chararray,p:chararray,o:chararray);
dump t  

This seems to run OK in pig until the end when I find out I didn't get any data.

Rather than writing unit tests (I'm not quite sure how) or using the debugger,  I've been attacking this by adding logging statements

Right now I see

2013-08-08 21:16:46,275 INFO com.ontology2.bakemono.primitiveTriple.LineProcessingRecordReader: Initializing Reader
2013-08-08 21:16:46,280 INFO com.ontology2.bakemono.primitiveTriple.LineProcessingRecordReader: nextKeyValue() returns true
2013-08-08 21:16:46,281 INFO org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigRecordReader: Current split being processed hdfs://cerebus:9000/005limeZ/part-r-00367.nt.gz:0+42504
2013-08-08 21:16:46,281 INFO com.ontology2.bakemono.primitiveTriple.LineProcessingRecordReader: Initializing Reader
2013-08-08 21:16:46,286 INFO com.ontology2.bakemono.primitiveTriple.LineProcessingRecordReader: nextKeyValue() returns true
2013-08-08 21:16:46,287 INFO org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigRecordReader: Current split being processed hdfs://cerebus:9000/005limeZ/part-r-00041.nt.gz:0+42411
2013-08-08 21:16:46,287 INFO com.ontology2.bakemono.primitiveTriple.LineProcessingRecordReader: Initializing Reader

Note that we have log statements on getCurrentKey() and getCurrentValue() but it appears that these functions never get called.  I think this is odd because nextKeyValue() is coming back true which I think would make the iteration continue.

**Comment by paulhoule** [comment]
I think the example I copied from the documentation at 

http://pig.apache.org/docs/r0.10.0/udf.html#load-store-functions

was incorrect because it incorrectly interpreted the sense of nextKeyValue().

Now I get this error,  and I bet it's because Pig wants some data structure different from a Text.

org.apache.pig.backend.executionengine.ExecException: ERROR 1071: Cannot convert a generic_writablecomparable to a String
    at org.apache.pig.data.DataType.toString(DataType.java:1105)
    at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POCast.getNext(POCast.java:928)
    at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:340)
    at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:372)
    at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNext(POForEach.java:297)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapBase.runPipeline(PigGenericMapBase.java:283)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapBase.map(PigGenericMapBase.java:278)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapBase.map(PigGenericMapBase.java:64)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:144)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:370)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1149)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

**Comment by paulhoule** [comment]
Passing Strings into the Tuple did the trick.
