### ISSUE TITLE
Instantiation exception creating EntityCentricMapper

### ISSUE THREAD

**Issue by paulhoule** [paulhoule/infovore#94]
Trying to run a minimal test job in AWS

```
haruhi run job -clusterId tinyAwsCluster extractIsA -dir s3n://basekb-now/2013-12-08-00-00/sieved \
 -input a/a-m-00000.nt.gz \
 -prefix http://rdf.basekb.com/ns/ \
 -type skiing.ski_area \
 -output s3n://basekb-sandbox/only-ski-tiny
```

It appears to blow up while creating the mapper,

```
2013-12-15 18:10:50,245 WARN org.apache.hadoop.mapred.Child (main): Error running child
java.lang.RuntimeException: java.lang.InstantiationException
    at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:115)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:726)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:375)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1132)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)
Caused by: java.lang.InstantiationException
    at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:113)
    ... 7 more
```

**Comment by paulhoule** [comment]
I just realized I'd never written a test for said Mapper,  so let's do it and hope the problem turns up.

**Comment by paulhoule** [comment]
Oops.  this turned out to be an abstract class,  it also has a lot of junk in it,  such as configuration material that is not getting wired up.  Write that test and get back in the game.
